# Generated by Django 4.2.5 on 2025-06-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customeruser_adress_customeruser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='address',
            new_name='adress',
        ),
    ]
