# Generated by Django 4.2.5 on 2025-06-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customeruser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
