# Generated by Django 4.2.5 on 2025-07-09 05:00

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', user.models.CustomerUserManager()),
            ],
        ),
    ]
