# Generated by Django 4.2.5 on 2025-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
